### ISSUE TITLE
Implement internal scoring system

### ISSUE THREAD

**Issue by pinpox** [megaclan3000/megaclan3000#69]
https://megaclan3000.de/scoreboard

#126 suggests we can use a parser to read all events that occured during a match
from a demo file that is uploaded and parsed.

- The scoreboard should show all players of the clan, ranked by their internal
- score, called `megascore`.  A clan match is considered any match that involves
- at least two clan members.  The score points are calculated based on
- performance in clan-matches.

The scoring system should factor in various data points from the demo file and
apply a weighting to give points to the players total score. The scoring is
calculated as shown in the table below
https://megaclan3000.de/scoreboard

#126 suggests we can use a parser to read all events that occured during a match
from a demo file that is uploaded and parsed.

- The scoreboard should show all players of the clan, ranked by their internal
- score, called `megascore`.  A clan match is considered any match that involves
- at least two clan members.  The score points are calculated based on
- performance in clan-matches.

The scoring system should factor in various data points from the demo file and
apply a weighting to give points to the players total score. The scoring is
calculated as shown in the tables below

### Match and Rounds
| Event       | Points given |
|-------------|--------------|
| Won match   | 100          |
| Won round   | 10           |
| Bomb plant  | 2            |
| Bomb defuse | 2            |
| MVP star    | 10           |

### Kills and Assists
| Event            | Points given |
|------------------|--------------|
| Kill             | 2            |
| Assist           | 1            |
| Flash-assist     | 1            |
| 3-Kill bonus     | 1            |
| 4-Kill bonus     | 2            |
| 5-Kill bonus     | 5            |
| Entry-Frag bonus | 1            |
| 1v2 clutch bonus | 1            |
| 1v3 clutch bonus | 2            |
| 1v3 clutch bonus | 3            |
| 1v4 clutch bonus | 4            |
| 1v5 clutch bonus | 5            |

### Teamdamage
| Event           | Points given |
|-----------------|--------------|
| Teamkill        | -5           |
| Team-Flash      | -2           |
| Teamdamage done | - Teamdamage |

### Other
| Event                 | Points given |
|-----------------------|--------------|
| Kicked from server    | -100         |
| Die with nade in hand | -5           |
| Play without clantag  | no points    |

Total match score weighted with:
Difficulty match D_m = Average enemy ranks / own rank [0 to 1]

**Comment by pinpox** [comment]
E.g. collapsible with "ADR" chart with multiple datasets (one per player)

**Comment by manuliner** [comment]
![e9ad3f2b-d0f6-417b-9813-b3b6499712c2](https://user-images.githubusercontent.com/5088151/88050598-6f698100-cb57-11ea-905a-1539ee05ab7e.jpg)

**Comment by manuliner** [comment]
Ich fände noch so sonderpunkte/Achievments witzig die irgendwelche blöden sachen belohnen oder bestrafen die beim zocken schon vorgekommen sind 


z.b. 

- Kick from Server wegen TK
- Sterben mit granate in der Hand
- 1000 Dmg an teammate mit granaten hits (nicht der explosiionsschaden, sondern wenn man jemanden mit einer granate trifft und die abprallt)
- (meisten Kills / mehr als 5 ) im Warm Up mit Messer
- spielen ohne clan tag
- Match mit gesamt dmg unter wert X
- Match mit gesamt dmg üver wert X

**Comment by pinpox** [comment]
> Ich fände noch so sonderpunkte/Achievments witzig die irgendwelche blöden sachen belohnen oder bestrafen die beim zocken schon vorgekommen sind
> 
> z.b.
> 
> * Kick from Server wegen TK
> * Sterben mit granate in der Hand
> * 1000 Dmg an teammate mit granaten hits (nicht der explosiionsschaden, sondern wenn man jemanden mit einer granate trifft und die abprallt)
> * (meisten Kills / mehr als 5 ) im Warm Up mit Messer
> * spielen ohne clan tag
> * Match mit gesamt dmg unter wert X
> * Match mit gesamt dmg üver wert X

Nice, ich aktaualisiere oben die tabelle.

**Comment by pinpox** [comment]
For reference, here is a list of data that is available from the parser:
https://pkg.go.dev/github.com/markus-wa/demoinfocs-golang/v2/pkg/demoinfocs/events?tab=doc
The link shows the event **types** that can occur on each tick of the server. Each one of them has additional information (click to see), e.g. for the EvenType `Kill` there are additional fields:
```go
type Kill struct {
	Weapon            *common.Equipment
	Victim            *common.Player // May be nil if the demo is partially corrupt (player is 'unconnected', see #156 and #172).
	Killer            *common.Player // May be nil for world damage (EqWorld) or if the demo is partially corrupt (player is 'unconnected', see #156 and #172).
	Assister          *common.Player
	PenetratedObjects int
	IsHeadshot        bool
}
```

Browes the docs linked for more information on what's available after parsing, these are the values we can use to calculate scores.

**Comment by pinpox** [comment]
A few more thoughts along the progress of implementing this:
- We should use the `median` instead of the `arithmetic mean` function to determine match difficulty from the ranks
- Would be nice to have "trophies" like `Warmup Master` (most kills in warmup), `HE Expert` (most kills with HE)... that players can have and take away from each other
- The `Gamestate` struct from the parser lib might provide more useful information that could be added to the output of `demoparser.Parse()`

The current state of the parsing implementation takes a demo file as input and produces a `Match` struct with the following structure. This should be the basic form of extracted data before processing or doing calculations on it. We should make sure all other necessary calculations on additional information that might be shown in the frontend and saved to the database are possible to calculate with this fields. Otherwise we might to extract more:
```go
type Match struct {
	// The ID of the match
	ID string

	// The time and date when the match took place
	Time time.Time

	// Map of the match
	Map string

	// The rounds of the match. This is the main source of information we can
	// use later on.
	Rounds []Round
}

// Round holds the result of parsing all ticks of a match that correspond to a
// single round.
type Round struct {

	// Round number
	Number int

	// Tick at which the round started
	TickStart int

	// Tick at which the round ended
	TickEnd int

	// Team that won the round, either "T" or "CT"
	TeamWon string

	// If the bomb was planted during the round
	BombPlanted bool

	// If the bomb was defused during the round
	BombDefused bool

	// If the bomb exploded during the round
	BombExploded bool

	// List of players that where presend in the round
	Players []Player
}

type Player struct {
	// SteamID of the player
	ID string

	// The the player was on during the round, "T" or "CT"
	Team string

	// If the player won the round
	Won bool

	// If the player received a MVP star for the round
	Mvp bool

	// Reason for the received MVP star
	MvpReason string

	// If the player planted the bomb during the round
	BombPlanted bool

	// If the player defused the bomb during the round
	BombDefused bool

	// Number the player fired during the round
	ShotsFired int

	// Number of shots the player it during the round
	ShotsHit int

	// Number of headshots that the player hit during the round
	Headshots int

	// Number of kills and assists the player made during the round
	Kills []Kill

	// Damages he did during the round, summarized to victims. This slice will
	// have a maximum lenght of the numbers of players of both teams
	// (Competitive: 10) if he damaged all players in the round of both teams.
	Victims []DamageVictim
}

// Kill holds the information about a kill that occured during a round, as
// parsed from the demo file
type Kill struct {

	// Tick at which the kill was made
	Tick int

	// True if it was a assist, false if it was a kill
	Assist bool

	// SteamID of the victim
	VictimID string

	// SteamID of the player he was assisted by, might be nil
	AssistID string

	// If it was an assist, the steamID of the player he assisted. This is nil
	// if it was a kill
	AssistedID string

	// The weapon used by the player at the time of the kill. He might have
	// used other weapons before that contributed damage, the last weapon used
	// is recorded.
	WeaponUsedID int
}

type DamageVictim struct {

	// SteamID of the player he damaged, might be on either team
	DamagedID string

	// The weapon used to inflict the most amount of damage to the this victim.
	MostDamageWeaponID int

	// Amount of damage inflicted to this victim in total
	Amount int
}
```

**Comment by pinpox** [comment]
The demo files should be "validated" before parsing. Valid demos should:
- Have at least 2 clan members in one team
- Have no clan members in different teams (no friendly matches parsed)
- Have not already been parsed (check ID/hash)

**Comment by pinpox** [comment]
Proposed new front-end endpoints and elements:
- `/scoreboard` showing score of all players
- `/match/<hash>` Match viewer for match `<hash>` with details about the match
- `Matches` tab in player details view showing points earned in matches, match entries linked to `/match/<hash>

**Comment by pinpox** [comment]
The scores calculated from the parsed demos should be saved to the database. 
The schema for the table should hold the match scores for each player, aswell as some extra information we might want to show in the scoreboard, like how much points where awarded by which things.:

| Column           | Type   | Description                            |
|------------------|--------|----------------------------------------|
| match_id         | int    | ID of the match (hash)                 |
| steam_id         | string | ID of the player                       |
| score_match      | int    | Points earned from won matches         |
| score_round      | int    | Points earned from won rounds          |
| score_plant      | int    | Points earned from planting bomb       |
| score_defuse     | int    | Points earned from defusing bomb       |
| score_mvp        | int    | Points earned from MVP stars           |
| score_kill       | int    | Points earned from kills               |
| score_assist     | int    | Points earned from assist              |
| score_3k         | int    | Points earned from 3-kills             |
| score_4k         | int    | Points earned from 4-kills             |
| score_5k         | int    | Points earned from aces                |
| score_entryfrag  | int    | Points earned from entryfrag           |
| score_clutchv1   | int    | Points earned from clutches v1         |
| score_clutchv2   | int    | Points earned from clutches v2         |
| score_clutchv3   | int    | Points earned from clutches v3         |
| score_clutchv4   | int    | Points earned from clutches v4         |
| score_clutchv5   | int    | Points earned from clutches v5         |
| score_teamkill   | int    | Points lost due to teamkills           |
| score_teamflash  | int    | Points lost due to teamflashes         |
| score_teamdamage | int    | Points lost due to teamdamage          |
| score_kick       | int    | Points lost due to kick                |
| score_noweapon   | int    | Points lost due to dying with HE/knive |

**Comment by pinpox** [comment]
# Roadmap
Here is a general roadmap to follow for the implementation of the demo-parsing functionality. I will be updating this comment along the way.

- [X] remove SQL database. No longer needed, see #131, will be replaced
- [ ] Finish implementing demo-parsing to return all necessary data
- [ ] Add a mongoDB database to store parsed demos. This seems the best fitting option for the type of data we have, since it's not really easy to store in a relational database.
- [ ] Store parsed data in new mongoDB
- [ ] Add a mechanism for uploading the demo files or better fetch them automatically from the steam API
- [ ] Implement the corresponding front-end parts to show the scoreboard
